In [2]:
import pandas as pd
import numpy as np

In [3]:
df= pd.read_csv('upi_transactions_2024-selected-columns.csv')

In [4]:
df.head()

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank
3,TXN0000000004,2024-01-07 10:09:17,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI
4,TXN0000000005,2024-01-23 19:04:23,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis

In [5]:
df.shape # 2.5 lakh rows, 10 columns

(250000, 10)

In [6]:
df.isnull().sum()

transaction id        0
timestamp             0
transaction type      0
merchant_category     0
amount (INR)          0
transaction_status    0
sender_age_group      0
receiver_age_group    0
sender_state          0
sender_bank           0
dtype: int64

In [7]:
df= df.rename(columns= {'sender_bank':'remitter_bank'})

In [8]:
df.head(3)

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,remitter_bank
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank

In [9]:
total_transactions=df['transaction id'].count() # total transactions
print(total_transactions)

250000

In [10]:
total_transaction_value=df['amount (INR)'].sum() # total transaction value
print(total_transaction_value)

327939009

In [11]:
avg_transaction_amount=df['amount (INR)'].mean() # avg transaction amount
print(avg_transaction_amount)

1311.756036

In [12]:
median_transaction_amount=df['amount (INR)'].median() # in order to identify outliers
print(median_transaction_amount)

629.0

In [13]:
df['transaction_status'].unique()

array(['SUCCESS', 'FAILED'], dtype=object)

In [14]:
successful_transactions= (df['transaction_status']=='SUCCESS').sum()
print(successful_transactions)

237624

In [15]:
failed_transactions= (df['transaction_status']=='FAILED').sum()
print(failed_transactions)

12376

In [16]:
success_rate = (successful_transactions / total_transactions) * 100
print(success_rate)

95.0496

In [17]:
failure_rate = (failed_transactions / total_transactions) * 100
print(failure_rate)

4.9504

In [18]:
p2p_count= (df['transaction type']=='P2P').sum()
print(p2p_count)

112445

In [19]:
p2m_count= (df['transaction type']=='P2M').sum()
print(p2m_count)

87660

In [20]:
print("P2P + P2M:", p2p_count + p2m_count)
print("Total Transactions:", total_transactions)

P2P + P2M: 200105
Total Transactions: 250000

In [21]:
df['transaction type'].unique()

array(['P2P', 'P2M', 'Bill Payment', 'Recharge'], dtype=object)

In [22]:
Bill_Payment = (df['transaction type']=='Bill Payment').sum()
print(Bill_Payment)

37368

In [23]:
Recharge = (df['transaction type']=='Recharge').sum()
print(Recharge)

12527

In [24]:
print("Success + Failed:", successful_transactions + failed_transactions)
print("Total Transactions:", total_transactions)

Success + Failed: 250000
Total Transactions: 250000

In [25]:
# Which type of UPI transaction has the highest volume, transaction value, average amount, and failure rate?
print("total transactions count of p2p", p2p_count)
sum_amount_p2p = df[(df['transaction type']=='P2P')]['amount (INR)'].sum()
print("Total Transaction Value of p2p", sum_amount_p2p)
avg_p2p_amount= df[(df['transaction type']=='P2P')]['amount (INR)'].mean()
print("avg  Transaction Value of p2p",  avg_p2p_amount)
p2p_failed_transactions = (
    (df[df['transaction type'] == 'P2P']['transaction_status'] == 'FAILED').sum()
)

failure_rate_p2p = (p2p_failed_transactions / p2p_count) * 100

print("P2P Failed Transactions:", p2p_failed_transactions)
print("P2P Failure Rate:", failure_rate_p2p, "%")

total transactions count of p2p 112445
Total Transaction Value of p2p 147154648
avg  Transaction Value of p2p 1308.6811152118814
P2P Failed Transactions: 5575
P2P Failure Rate: 4.957979456623238 %

In [26]:
# P2M analysis

p2m_count = (df['transaction type'] == 'P2M').sum()

p2m_share = (p2m_count / total_transactions) * 100

p2m_total_value = df.loc[
    df['transaction type'] == 'P2M',
    'amount (INR)'
].sum()

p2m_avg_amount = df.loc[
    df['transaction type'] == 'P2M',
    'amount (INR)'
].mean()

p2m_failed_transactions = (
    (df['transaction type'] == 'P2M') &
    (df['transaction_status'] == 'FAILED')
).sum()

p2m_failure_rate = (
    p2m_failed_transactions / p2m_count
) * 100

print("P2M Transactions:", p2m_count)
print("P2M Share:", p2m_share, "%")
print("P2M Total Transaction Value:", p2m_total_value)
print("P2M Average Transaction Amount:", p2m_avg_amount)
print("P2M Failed Transactions:", p2m_failed_transactions)
print("P2M Failure Rate:", p2m_failure_rate, "%")

P2M Transactions: 87660
P2M Share: 35.064 %
P2M Total Transaction Value: 115717567
P2M Average Transaction Amount: 1320.0726328998403
P2M Failed Transactions: 4339
P2M Failure Rate: 4.9498060689025785 %

In [27]:
# Bill Payment analysis

bill_count = (df['transaction type'] == 'Bill Payment').sum()

bill_share = (bill_count / total_transactions) * 100

bill_total_value = df.loc[
    df['transaction type'] == 'Bill Payment',
    'amount (INR)'
].sum()

bill_avg_amount = df.loc[
    df['transaction type'] == 'Bill Payment',
    'amount (INR)'
].mean()

bill_failed_transactions = (
    (df['transaction type'] == 'Bill Payment') &
    (df['transaction_status'] == 'FAILED')
).sum()

bill_failure_rate = (
    bill_failed_transactions / bill_count
) * 100

print("Bill Payment Transactions:", bill_count)
print("Bill Payment Share:", bill_share, "%")
print("Bill Payment Total Transaction Value:", bill_total_value)
print("Bill Payment Average Transaction Amount:", bill_avg_amount)
print("Bill Payment Failed Transactions:", bill_failed_transactions)
print("Bill Payment Failure Rate:", bill_failure_rate, "%")

Bill Payment Transactions: 37368
Bill Payment Share: 14.947199999999999 %
Bill Payment Total Transaction Value: 48895743
Bill Payment Average Transaction Amount: 1308.4923731535002
Bill Payment Failed Transactions: 1824
Bill Payment Failure Rate: 4.881181759794476 %

In [28]:
# Recharge analysis

recharge_count = (df['transaction type'] == 'Recharge').sum()

recharge_share = (recharge_count / total_transactions) * 100

recharge_total_value = df.loc[
    df['transaction type'] == 'Recharge',
    'amount (INR)'
].sum()

recharge_avg_amount = df.loc[
    df['transaction type'] == 'Recharge',
    'amount (INR)'
].mean()

recharge_failed_transactions = (
    (df['transaction type'] == 'Recharge') &
    (df['transaction_status'] == 'FAILED')
).sum()

recharge_failure_rate = (
    recharge_failed_transactions / recharge_count
) * 100

print("Recharge Transactions:", recharge_count)
print("Recharge Share:", recharge_share, "%")
print("Recharge Total Transaction Value:", recharge_total_value)
print("Recharge Average Transaction Amount:", recharge_avg_amount)
print("Recharge Failed Transactions:", recharge_failed_transactions)
print("Recharge Failure Rate:", recharge_failure_rate, "%")

Recharge Transactions: 12527
Recharge Share: 5.0108 %
Recharge Total Transaction Value: 16171051
Recharge Average Transaction Amount: 1290.8957451903887
Recharge Failed Transactions: 638
Recharge Failure Rate: 5.092999121896703 %

In [29]:
#"P2P transactions account for the largest share of transaction volume (44.98%) and transaction value (~₹14.72 crore), while recharge transactions show the highest failure rate (5.09%), indicating a potential area for further investigation."

In [30]:
## TIMESTAMP ANALYSIS
## HOUR WISE ANALYSIS
print(df['timestamp'].dtype)
df['timestamp']= pd.to_datetime(df['timestamp']) ## object se datetime me convert kr liya
df['hour']= df['timestamp'].dt.hour ## extracted hour from datetime
df['hour'].value_counts().sort_index() ## how many transactions happened in each hour

object

hour
0      3388
1      2244
2      1685
3      1314
4      1247
5      1742
6      3501
7      5630
8      8349
9     10450
10    13904
11    16328
12    17516
13    15038
14    11472
15    12624
16    13992
17    18340
18    20064
19    21232
20    18506
21    16253
22     9364
23     5817
Name: count, dtype: int64

In [31]:
## no. of failed transaction by each hour
failed_transaction_per_hour= df[df['transaction_status'] == 'FAILED'].groupby('hour').size()
print(failed_transaction_per_hour)

hour
0      182
1      120
2       87
3       66
4       64
5       79
6      189
7      275
8      418
9      503
10     721
11     810
12     875
13     717
14     570
15     646
16     652
17     911
18     973
19    1093
20     904
21     772
22     471
23     278
dtype: int64

In [32]:
total_transaction_per_hour = df.groupby('hour').size()
print(total_transaction_per_hour)

hour
0      3388
1      2244
2      1685
3      1314
4      1247
5      1742
6      3501
7      5630
8      8349
9     10450
10    13904
11    16328
12    17516
13    15038
14    11472
15    12624
16    13992
17    18340
18    20064
19    21232
20    18506
21    16253
22     9364
23     5817
dtype: int64

In [33]:
failure_rate_per_hour = (failed_transaction_per_hour / total_transaction_per_hour) * 100
print(failure_rate_per_hour)

hour
0     5.371901
1     5.347594
2     5.163205
3     5.022831
4     5.132318
5     4.535017
6     5.398458
7     4.884547
8     5.006588
9     4.813397
10    5.185558
11    4.960804
12    4.995433
13    4.767921
14    4.968619
15    5.117237
16    4.659806
17    4.967285
18    4.849482
19    5.147890
20    4.884902
21    4.749892
22    5.029902
23    4.779096
dtype: float64

In [34]:
## Interestingly, the hour with the highest transaction volume (7 PM) is NOT the hour with the highest failure rate.
## failure rate is:
## 6 AM → 5.40% approximately

In [35]:
hourly_analysis = pd.DataFrame({
    'total_transactions': total_transaction_per_hour,
    'failed_transactions': failed_transaction_per_hour,
    'failure_rate': failure_rate_per_hour
})

hourly_analysis

      total_transactions  failed_transactions  failure_rate
hour
0                   3388                  182      5.371901
1                   2244                  120      5.347594
2                   1685                   87      5.163205
3                   1314                   66      5.022831
4                   1247                   64      5.132318
5                   1742                   79      4.535017
6                   3501                  189      5.398458
7                   5630                  275      4.884547
8                   8349                  418      5.006588
9                  10450                  503      4.813397
10                 13904                  721      5.185558
11                 16328                  810      4.960804
12                 17516                  875      4.995433
13                 15038                  717      4.767921
14                 11472                  570      4.968619
15                 12624                  646      5.117237
16                 13992                  652      4.659806
17                 18340                  911      4.967285
18                 20064                  973      4.849482
19                 21232                 1093      5.147890
20                 18506                  904      4.884902
21                 16253                  772      4.749892
22                  9364                  471      5.029902
23                  5817                  278      4.779096

In [37]:
df['day']= df['timestamp'].dt.day
df['day'].value_counts().sort_index() # no. of transactions happened each day

day
1     8191
2     8362
3     8119
4     8210
5     8282
6     8236
7     8157
8     8206
9     8127
10    8218
11    8323
12    8078
13    8245
14    8144
15    8181
16    8125
17    8226
18    8264
19    8308
20    8302
21    8266
22    8246
23    8138
24    8181
25    8283
26    8239
27    8302
28    8151
29    8167
30    7655
31    4068
Name: count, dtype: int64

In [41]:
# failed transactions per day
failed_transactions_per_day = df[(df['transaction_status']=='FAILED')].groupby('day').size()
failed_transactions_per_day

day
1     417
2     404
3     406
4     385
5     421
6     387
7     414
8     419
9     396
10    428
11    419
12    385
13    416
14    424
15    425
16    374
17    429
18    398
19    400
20    408
21    401
22    419
23    393
24    394
25    396
26    410
27    406
28    420
29    397
30    388
31    197
dtype: int64

In [43]:
total_transactions_per_day= df.groupby('day').size()
total_transactions_per_day

day
1     8191
2     8362
3     8119
4     8210
5     8282
6     8236
7     8157
8     8206
9     8127
10    8218
11    8323
12    8078
13    8245
14    8144
15    8181
16    8125
17    8226
18    8264
19    8308
20    8302
21    8266
22    8246
23    8138
24    8181
25    8283
26    8239
27    8302
28    8151
29    8167
30    7655
31    4068
dtype: int64

In [45]:
failure_rate_per_day= (failed_transactions_per_day/ total_transactions_per_day)*100
failure_rate_per_day

day
1     5.090953
2     4.831380
3     5.000616
4     4.689403
5     5.083313
6     4.698883
7     5.075395
8     5.106020
9     4.872647
10    5.208080
11    5.034242
12    4.766031
13    5.045482
14    5.206287
15    5.194964
16    4.603077
17    5.215171
18    4.816070
19    4.814636
20    4.914478
21    4.851198
22    5.081252
23    4.829196
24    4.816037
25    4.780876
26    4.976332
27    4.890388
28    5.152742
29    4.861026
30    5.068583
31    4.842675
dtype: float64

In [46]:
daily_analysis = pd.DataFrame({
    'total_transactions':total_transactions_per_day,
    'failed_transactions_per_day':failed_transactions_per_day,
    'failure_rate_per_day':failure_rate_per_day})
daily_analysis

     total_transactions  failed_transactions_per_day  failure_rate_per_day
day
1                  8191                          417              5.090953
2                  8362                          404              4.831380
3                  8119                          406              5.000616
4                  8210                          385              4.689403
5                  8282                          421              5.083313
6                  8236                          387              4.698883
7                  8157                          414              5.075395
8                  8206                          419              5.106020
9                  8127                          396              4.872647
10                 8218                          428              5.208080
11                 8323                          419              5.034242
12                 8078                          385              4.766031
13                 8245                          416              5.045482
14                 8144                          424              5.206287
15                 8181                          425              5.194964
16                 8125                          374              4.603077
17                 8226                          429              5.215171
18                 8264                          398              4.816070
19                 8308                          400              4.814636
20                 8302                          408              4.914478
21                 8266                          401              4.851198
22                 8246                          419              5.081252
23                 8138                          393              4.829196
24                 8181                          394              4.816037
25                 8283                          396              4.780876
26                 8239                          410              4.976332
27                 8302                          406              4.890388
28                 8151                          420              5.152742
29                 8167                          397              4.861026
30                 7655                          388              5.068583
31                 4068                          197              4.842675

In [47]:
df['day_of_week'] = df['timestamp'].dt.day_name()

In [48]:
df[['timestamp', 'day_of_week']].head()

            timestamp day_of_week
0 2024-10-08 15:17:28     Tuesday
1 2024-04-11 06:56:00    Thursday
2 2024-04-02 13:27:18     Tuesday
3 2024-01-07 10:09:17      Sunday
4 2024-01-23 19:04:23     Tuesday

In [49]:
df['day_of_week'].value_counts()

day_of_week
Monday       36495
Sunday       36003
Wednesday    35700
Tuesday      35540
Friday       35496
Thursday     35432
Saturday     35334
Name: count, dtype: int64

In [50]:
failed_transaction_per_day = df[df['transaction_status'] == 'FAILED'].groupby('day_of_week').size()

print(failed_transaction_per_day)

day_of_week
Friday       1694
Monday       1810
Saturday     1797
Sunday       1835
Thursday     1757
Tuesday      1702
Wednesday    1781
dtype: int64

In [51]:
total_transaction_per_day = df.groupby('day_of_week').size()

failure_rate_per_day = (failed_transaction_per_day / total_transaction_per_day) * 100

print(failure_rate_per_day)

day_of_week
Friday       4.772369
Monday       4.959584
Saturday     5.085753
Sunday       5.096797
Thursday     4.958794
Tuesday      4.788970
Wednesday    4.988796
dtype: float64

“UPI failure rates are slightly higher on weekends, reaching 5.10% on Sunday compared with 4.77% on Friday. This suggests weekend transactions may warrant further investigation, although the difference is relatively small.”

In [52]:
# monthly analysis
df['month'] = df['timestamp'].dt.to_period('M')

In [53]:
df['month'].value_counts().sort_index()

month
2024-01    21221
2024-02    19759
2024-03    21234
2024-04    20536
2024-05    21333
2024-06    20628
2024-07    21207
2024-08    21231
2024-09    20597
2024-10    21252
2024-11    20366
2024-12    20636
Freq: M, Name: count, dtype: int64

In [54]:
failed_transaction_per_month = (
    df[df['transaction_status'] == 'FAILED']
    .groupby('month')
    .size()
)

print(failed_transaction_per_month)

month
2024-01    1012
2024-02     954
2024-03    1142
2024-04    1009
2024-05    1038
2024-06    1040
2024-07    1061
2024-08    1033
2024-09    1061
2024-10    1007
2024-11    1009
2024-12    1010
Freq: M, dtype: int64

In [55]:
total_transaction_per_month = df.groupby('month').size()

In [56]:
failure_rate_per_month = (
    failed_transaction_per_month / total_transaction_per_month
) * 100

print(failure_rate_per_month)

month
2024-01    4.768861
2024-02    4.828180
2024-03    5.378167
2024-04    4.913323
2024-05    4.865701
2024-06    5.041691
2024-07    5.003065
2024-08    4.865527
2024-09    5.151236
2024-10    4.738378
2024-11    4.954336
2024-12    4.894359
Freq: M, dtype: float64

In [ ]:
# March highest at 5.38%; October lowest at 4.74%